#!/usr/bin/env bash

DIR="examples/cpp_models"   # Domain directory
LOG=/dev/stdout             # Log file output
REWIND=false
NUMRUN=50
NOOBSTAG="-l tag_noOppObs_TPOMCP.log tag/noobstag"
ROCKSAMPLE="-l rock_sample_TPOMCP.log rock_sample/rock_sample"
SIZE=7
NUMBER=8

set -e
make -C $DIR/tag
make -C $DIR/rock_sample




for i in 10  20 90
do
  echo "started " $i

  for j in -1 -2 -10
  do
    echo "started " $j
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --unsuccessful_reward $j
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --leaf_heuristic SARSOP --unsuccessful_reward $j
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --leaf_heuristic VI --unsuccessful_reward $j
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --check_default_policy --unsuccessful_reward $j
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --geometric_search_depth --unsuccessful_reward $j

    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --unsuccessful_reward $j --discount 0.7
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --leaf_heuristic SARSOP --unsuccessful_reward $j --discount 0.7
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --leaf_heuristic VI --unsuccessful_reward $j --discount 0.7
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --check_default_policy --unsuccessful_reward $j --discount 0.7
    bash runexp $NOOBSTAG --runs $NUMRUN --solver TPOMCP --depth $i --geometric_search_depth --unsuccessful_reward $j --discount 0.7
  done

  for j in -2 -5 -10
    do
      echo "started " $j
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --unsuccessful_reward $j
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --leaf_heuristic SARSOP --unsuccessful_reward $j
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --leaf_heuristic VI --unsuccessful_reward $j
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --check_default_policy --unsuccessful_reward $j
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --geometric_search_depth --unsuccessful_reward $j

      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --unsuccessful_reward $j --discount 0.7
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --leaf_heuristic SARSOP --unsuccessful_reward $j --discount 0.7
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --leaf_heuristic VI --unsuccessful_reward $j --discount 0.7
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --check_default_policy --unsuccessful_reward $j --discount 0.7
      bash runexp $ROCKSAMPLE --runs $NUMRUN --size $SIZE --number $NUMBER --solver TPOMCP --depth $i --geometric_search_depth --unsuccessful_reward $j --discount 0.7

    done
done


















